/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package metergas.vistas;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JPopupMenu;
import javax.swing.WindowConstants;
import metergas.controller.MeterGasController;
import metergas.model.views.ClienteIndustrialView;
import metergas.model.views.ClienteResidencialView;
import metergas.model.views.ClienteView;
import metergas.model.views.DomicilioView;
import metergas.vistas.clientes.JFrameBase;

/**
 *
 * @author eteodoro
 */
public class Home extends javax.swing.JFrame {

    private JFrame ventanaPrincipal;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        ventanaPrincipal = this;
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenuClientes = new javax.swing.JMenu();
        jMenuAlta = new javax.swing.JMenuItem();
        jMenuBaja = new javax.swing.JMenuItem();
        jMenuModificacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuClientes.setText("Clientes");
        jMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });

        jMenuAlta.setText("Alta");
        jMenuAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuAlta);

        jMenuBaja.setText("Baja");
        jMenuBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuBaja);

        jMenuModificacion.setText("Modificacion");
        jMenuModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuModificacion);

        jMenuBar.add(jMenuClientes);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActionPerformed
        javax.swing.JMenuItem source = (javax.swing.JMenuItem) evt.getSource();
        javax.swing.JPopupMenu parentPopup = (JPopupMenu) source.getParent();
        javax.swing.JMenu menu = (javax.swing.JMenu) parentPopup.getInvoker();

        JFrameBase vista = VistasManager.getInstance().getVista(String.format("%s.%s", menu.getActionCommand(),
                source.getActionCommand()));


        vista.addWindowListener(new WindowAdapter() {

            public void windowClosed(WindowEvent arg0) {
                JFrameBase vistaCerrada = (JFrameBase) arg0.getSource();
                vistaCerrada.clear();

                ventanaPrincipal.setFocusableWindowState(true);
                ventanaPrincipal.setVisible(true);
            }
        });

        vista.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        vista.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_jMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */

        /*
         * Instanciacion de parametria y clases de base
         *
         */
        
        MeterGasController mg = MeterGasController.getInstance();

        mg.inicializar();
        DomicilioView dv = new DomicilioView("Alem", "7", "5", "A", "1878", "Quilmes", "Buenos Aires");

        ClienteView cv = new ClienteResidencialView("Ronnie James", "Dio", "111111", 0, null, dv);
        mg.altaCliente(cv);

        cv = new ClienteResidencialView("Steve", "Harris", "222222", 0, null, dv);
        mg.altaCliente(cv);

        cv = new ClienteIndustrialView("Deep Purple", "123", "Responsable Inscripto", "333333", 0, null, dv);
        mg.altaCliente(cv);

        cv = new ClienteIndustrialView("Iron Maiden", "456", "Responsable Inscripto", "444444", 0, null, dv);
        mg.altaCliente(cv);

        mg.registrarMedicion(1, new Date(2012, 03, 10), 100);
        mg.registrarMedicion(1, new Date(2012, 05, 10), 200);
        mg.registrarMedicion(2, new Date(2012, 03, 10), 100);
        mg.registrarMedicion(2, new Date(2012, 05, 10), 200);
        mg.registrarMedicion(3, new Date(2012, 03, 10), 100);
        mg.registrarMedicion(3, new Date(2012, 05, 10), 200);
        mg.registrarMedicion(4, new Date(2012, 03, 10), 100);
        mg.registrarMedicion(4, new Date(2012, 05, 10), 200);
        
        
        /*
         * Invocacion de la ventana principal
         *
         * java.awt.EventQueue.invokeLater(new Runnable() {
         *
         * public void run() { new Home().setVisible(true); } });
         *
         */



    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuAlta;
    private javax.swing.JMenuItem jMenuBaja;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenuItem jMenuModificacion;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the ventanaPrincipal
     */
    public JFrame getVentanaPrincipal() {
        return ventanaPrincipal;
    }

    /**
     * @param ventanaPrincipal the ventanaPrincipal to set
     */
    public void setVentanaPrincipal(JFrame ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
    }
}
