CREATE TABLE Cliente (id int IDENTITY NOT NULL, estado nvarchar(100) NOT NULL, tipo nvarchar(200) NOT NULL, PRIMARY KEY (id));
CREATE TABLE ClienteResidencial (clienteid int NOT NULL, nombre nvarchar(100) NOT NULL, apellido nvarchar(100) NOT NULL, dni nvarchar(100) NOT NULL);
CREATE TABLE Medicion (clienteId int NOT NULL, valor float(10) NOT NULL, liquidado bit NOT NULL, fecha datetime NOT NULL);
CREATE TABLE Concepto (codigo int NOT NULL, concepto nvarchar(100) NOT NULL, valor float(10) NOT NULL, PRIMARY KEY (codigo));
CREATE TABLE Factura (nro int IDENTITY NOT NULL, clienteId int NOT NULL, fecha datetime NOT NULL, subsidio float(10) NOT NULL, consumo float(10) NOT NULL, PRIMARY KEY (nro));
CREATE TABLE Domicilio (calle nvarchar(100) NULL, altura nvarchar(10) NULL, piso nvarchar(10) NULL, departamento nvarchar(10) NULL, codigoPostal nvarchar(100) NULL, localidad nvarchar(100) NULL, provincia nvarchar(100) NULL, clienteId int NOT NULL);
CREATE TABLE ItemFactura (nroFactura int NULL, concepto nvarchar(100) NULL, valor float(10) NULL);
CREATE TABLE ClienteIndustrial (clienteId int NOT NULL, razonSocial nvarchar(100) NOT NULL, nroIBBB nvarchar(100) NOT NULL, condicionFiscal nvarchar(100) NOT NULL, CUIT nvarchar(100) NOT NULL);
ALTER TABLE ItemFactura ADD CONSTRAINT FKItemFactur128778 FOREIGN KEY (nroFactura) REFERENCES Factura (nro);
ALTER TABLE ClienteIndustrial ADD CONSTRAINT FKClienteInd480670 FOREIGN KEY (clienteId) REFERENCES Cliente (id);
ALTER TABLE ClienteResidencial ADD CONSTRAINT FKClienteRes62322 FOREIGN KEY (clienteid) REFERENCES Cliente (id);
ALTER TABLE Medicion ADD CONSTRAINT FKMedicion901418 FOREIGN KEY (clienteId) REFERENCES Cliente (id);
ALTER TABLE Factura ADD CONSTRAINT FKFactura936811 FOREIGN KEY (clienteId) REFERENCES Cliente (id);
ALTER TABLE Domicilio ADD CONSTRAINT FKDomicilio863722 FOREIGN KEY (clienteId) REFERENCES Cliente (id);
CREATE INDEX ClienteResidencial_clienteid ON ClienteResidencial (clienteid);
CREATE INDEX Medicion_clienteId ON Medicion (clienteId);
CREATE INDEX Factura_clienteId ON Factura (clienteId);
CREATE INDEX Domicilio_clienteId ON Domicilio (clienteId);
CREATE INDEX ClienteIndustrial_clienteId ON ClienteIndustrial (clienteId);
