/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package metergas.vistas.clientes;

import metergas.vistas.clientes.contratos.FormularioClienteInterface;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import metergas.controller.MeterGasController;
import metergas.model.views.ViewDataItem;

/**
 *
 * @author eteodoro
 */
public class Alta extends JFrameBase {

    private FormularioClienteInterface formulario = null;

    /**
     * Creates new form Alta
     */
    public Alta() {
        initComponents();
        cargarCombo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboTiposCliente = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        pnlFormulario = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jComboTiposCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboTiposCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTiposClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de cliente");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 30));

        btnCrear.setText("Crear");
        btnCrear.setEnabled(false);
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboTiposCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 265, Short.MAX_VALUE))
                    .addComponent(pnlFormulario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCrear)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboTiposCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(pnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(btnCrear)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboTiposClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTiposClienteActionPerformed
        formulario = null;
        pnlFormulario.removeAll();
        this.pack();
        if (jComboTiposCliente.getSelectedItem() == null || jComboTiposCliente.getSelectedItem().toString().equals("Seleccione")) {
            btnCrear.setEnabled(false);
            return;
        }
        btnCrear.setEnabled(true);
        ViewDataItem itemSeleccionado = (ViewDataItem) jComboTiposCliente.getSelectedItem();
        
        try {
            try {
                JPanel formularioView = (JPanel) Class.forName(itemSeleccionado.getCodigo()).newInstance();
                formularioView.setVisible(true);

                pnlFormulario.add((JPanel) formularioView);
                formulario = (FormularioClienteInterface)formularioView;
                this.pack();
            } catch (InstantiationException ex) {
                Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jComboTiposClienteActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        try {
            MeterGasController.getInstance().altaCliente(formulario.getCliente());
            
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JComboBox jComboTiposCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlFormulario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clear() {
        jComboTiposCliente.setSelectedIndex(0);

    }

    private void cargarCombo() {
        Collection<ViewDataItem> tiposCliente = MeterGasController.getInstance().getTiposCliente();

        jComboTiposCliente.removeAllItems();

        jComboTiposCliente.addItem("Seleccione");
        for (ViewDataItem viewDataItem : tiposCliente) {
            jComboTiposCliente.addItem(viewDataItem);
        }
    }
}
